dist: xenial
language: python
python:
  - "3.8"

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

env:
  global:
    - ENV_FOR_DYNACONF=travis
    - DYNACONF_DATABASE_URL="postgresql://postgres@localhost:5432/taranova-travel"

install:
  - sudo add-apt-repository --yes ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install --yes
    python3-gdal
    libgdal-dev
    gdal-bin
    postgresql-9.6-postgis-2.4
    postgis
  - pip install pipenv --upgrade
  - sudo apt-get install python3-gdal libgdal-dev
#  - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
#    - sudo apt-get -qq remove postgis
#    - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
#    - sudo apt-get update -qq
#    - sudo apt-get install -qq bison flex python-lxml libfribidi-dev swig cmake
#    librsvg2-dev colordiff postgis postgresql-9.6-postgis-2.0-scripts libpq-dev
#    libpng12-dev libjpeg-dev libgif-dev libgeos-dev libgd2-xpm-dev libfreetype6-dev
#    libfcgi-dev libcurl4-gnutls-dev libcairo2-dev libgdal1-dev libproj-dev
#    libxml2-dev python-dev php5-dev libexempi-dev lcov lftp
  - make venv static

before_script:
  - make resetdb
  - psql -U postgres -c "create extension postgis" -d taranova-travel

script:
  - make test

after_success:
  - codecov

cache: pip

jobs:
  include:
    - stage: test
      python: '3.8'
